services:
  backend:
    build:
      context: ./backend/main
      dockerfile: Dockerfile
    container_name: roble_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn main.app:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: roble_front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

